### PR TITLE
Issue #3: Implementation of multi-platform packaging with PyInstaller

### LINKED ISSUE #3: Implement multi-platform packaging and installer

### PR DESCRIPTION
**Pull request by nutjob4life**
Hi folks; this contains changes to support packaging the PDS Inspect Tool for macOS, Windows, and Linux environments. The `README.rst` contains details on how to do it. This should provide support to [PDS-660](https://oodt.jpl.nasa.gov/jira/browse/PDS-660).

Resolves #3

### CODE REVIEW

**Review by galenatjpl — COMMENTED** [review]
This all looks good, except in principle I don't think we should be committing IDE-specific files (i.e. "PDS Inspect Tool.sublime-project") to the repo.  Different developers will have different types of files, and different IDEs, etc...
I would remove this file, and add an expression for "*.sublime-project" to the .gitignore.

**Comment by nutjob4life** [comment]
Removed. (Is "Sublime Text" really an IDE? It's hard to tell these days! 😄)

**Comment by galenatjpl** [comment]
Probably borderline IDE :)
It can do a lot of cool magic stuff!

On Apr 10, 2019, at 5:24 PM, Sean Kelly <notifications@github.com<mailto:notifications@github.com>> wrote:


Removed. (Is "Sublime Text" really an IDE? It's hard to tell these days! 😄)

**Review by jordanpadams — APPROVED** [review]
Per comments from @galenatjpl and update from @nutjob4life we are good for merge.

**Pull request merged**
