### PR TITLE
NASA-PDS/devops#10

### PR DESCRIPTION
**Pull request by nutjob4life**
##  📜 Summary

Merge this if you dare to make this repository look a bit more like the PDS Template Repository (Python).

👉 **Note:** Since this is an ancient Python 2.7 repository that does not integrate with any of our workflows or—for that matter—any semblance of modern tooling, the purpose of this rollout is mostly just to get issue/PR templates and community health notices in place. As a small bonus, it also fixes broken hyperlinks in the `README.rst`.

This repository will eventually be archived and the features it provided re-developed in a web app.

## 🩺 Test Data and/or Report

Hilarious.

## 🧩 Related Issues

- NASA-PDS/devops#10

### CODE REVIEW

**Review by tloubrieu-jpl — APPROVED** [review]
I guess that should not break the application... Go to go for me

**Comment by nutjob4life** [comment]
Thanks @tloubrieu-jpl!

**Comment by MJJoyce** [comment]
> I guess that should not break the application...

power-hayden-christensen

**Comment by MJJoyce** [comment]
+1 to this. Looks great and sorry for missing the review request!

**Pull request merged**
